// ----------------Read Me-------------------
// This is the part which makes the layout of the page with different compoaents around it 
// like navbar and footer in this case



import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
// import Navbar from "@/components/Navbar";
import Footer from "../components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar></Navbar>
        {/* <Navbar/> */}
        {children}
        {/* <Footer/> */}
        <Footer/>
        </body>
    </html>
  );
}
